FROM golang:1.21-bookworm as builder

WORKDIR /app
COPY . .
RUN go build -o server ./cmd/server/main.go


FROM debian:bookworm

COPY --from=builder ./app/server server

EXPOSE 2000/tcp
ENTRYPOINT /server